parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  semi: "off"
  "@typescript-eslint/semi": "error"
  "@typescript-eslint/member-ordering": "error"
